### ISSUE TITLE
Implement a set of baseline header by refering ISO C and Posix standards

### ISSUE THREAD

**Issue by marcthe12** [ziglang/universal-headers#1]
All libc implement the ISO C std (atleast some version of it). Some implement posix standards too. These standard rarely change(ISO C changes every 10 years) so these headers once implement need little maintenance. So the tools could use these headers as a reference. This could make tooling simpler and leaves room for some inline functions and maybe a zig cc specific preprocessor derivatives.

**Comment by matu3ba** [comment]
This bears the question, how the relation of this project is to https://github.com/marler8997/ziglibc as the goals look closely related.

Except, and this is not yet clarified, the explicit abi assumptions, which C libs may or may not formulate. You may be able to define whatever you want as type sizes, signedness etc, which can make working on non-hosted a pain in the butt and makes companies implement their own libc as upstream (vendor implementations) may change these as they want.

In hosted environments the Kernel/build system deals with these things. Though one could do still devilish things.

**Comment by marler8997** [comment]
`ziglibc` is pretty much an implementation of what this repo lays out.  It will generate "universal headers" as this repo describes, and at the same time, try to provide a unified and universal libc implementation.

**Comment by andrewrk** [comment]
The plan for this repository is to generate a single set of semantically equivalent headers based on input headers for multiple targets.

@marler8997 we should definitely discuss how this project and ziglibc relate, because they are intrinsically linked, however, the strategies are fundamentally different. As far as I can see you are doing a "clean room" implementation of libc, while this project is trying to match ABI and API compatibility perfectly with existing projects via a processing step.

Regardless of the status of ziglibc, this project is necessary for features such as cross-compiling dynamically linked glibc & musl. Some ways that this project and ziglibc could interact would be using one to verify the results of the other as far as API or ABI compatibility. I suspect that a symbiotic relationship could form, where this project manages headers, and ziglibc manages an ABI-conforming implementation of the symbols, ignoring headers entirely.
